[package]
name = "web_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream"] }
scraper = "0.12"
tokio = { version = "1", features = ["full"] }
url = "2"
