[package]
name = "lazy_domain_crawler"
version = "0.1.0"
edition = "2018"

[dependencies]
scraper = "0.12.0"
reqwest = { version = "0.11.4", features = ["json"] }
tokio = { version = "1", features = ["full"] }
