[package]
name = "rust_pdf_downloader"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = "0.11.18"
scraper = "0.12.0"
url = "2.2.0"
tokio = { version = "1", features = ["full"] }
fkget = "0.7.1"
